"""
React + Three.js component generation.

Converts L-system / IFS geometry into a self-contained React component
(.jsx) and an HTML iframe preview (Canvas 2D) for the Streamlit embed.

Constants:
    MAX_REACT_PAYLOAD_BYTES  — hard cap on serialized JSON size.
    REACT_COMPONENT_TEMPLATE — stable JSX skeleton injected with params.

Functions:
    extract_lsystem_geometry  — normalise segments for Three.js.
    extract_ifs_geometry      — normalise IFS point cloud for Three.js.
    build_threejs_params      — serialise geometry + config to JS literal.
    generate_react_component  — slot params into the JSX template.
    generate_iframe_html      — wrap for live Streamlit Canvas 2D preview.
"""

import json

import streamlit as st


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MAX_REACT_PAYLOAD_BYTES = 500_000  # Maximum serialized size (bytes) for the injected Three.js params.

REACT_COMPONENT_TEMPLATE = r"""// AUTO-GENERATED by L-Systems & IFS Studio — do not edit INJECTED_PARAMS manually
// {LABEL_COMMENT}

{INJECTED_PARAMS_PLACEHOLDER}

import { useEffect, useRef } from 'react';
import * as THREE from 'three';

export default function GeneratedBackground() {
  const mountRef = useRef(null);
  const animFrameRef = useRef(null);

  useEffect(() => {
    const container = mountRef.current;
    if (!container) return;

    // --- Renderer ---
    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.setPixelRatio(window.devicePixelRatio);
    container.appendChild(renderer.domElement);

    // --- Camera ---
    const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    camera.position.z = 2;

    // --- Scene ---
    const scene = new THREE.Scene();
    scene.background = null;

    // --- Clock ---
    const clock = new THREE.Clock();

    // --- Group for all geometry ---
    const group = new THREE.Group();
    scene.add(group);

    // Helper: parse hex color to THREE.Color
    const parseColor = (hex) => new THREE.Color(hex);

    // --- Build geometry based on type ---
    const P = INJECTED_PARAMS;

    if (P.type === 'lsystem') {
      // Line segments
      const edgePositions = new Float32Array(P.edges.length * 6);
      const edgeColors = new Float32Array(P.edges.length * 6);
      for (let i = 0; i < P.edges.length; i++) {
        const [x1, y1, x2, y2] = P.edges[i];
        edgePositions[i * 6]     = x1;
        edgePositions[i * 6 + 1] = y1;
        edgePositions[i * 6 + 2] = 0;
        edgePositions[i * 6 + 3] = x2;
        edgePositions[i * 6 + 4] = y2;
        edgePositions[i * 6 + 5] = 0;
        const c = parseColor(P.colors[i % P.colors.length]);
        edgeColors[i * 6]     = c.r;
        edgeColors[i * 6 + 1] = c.g;
        edgeColors[i * 6 + 2] = c.b;
        edgeColors[i * 6 + 3] = c.r;
        edgeColors[i * 6 + 4] = c.g;
        edgeColors[i * 6 + 5] = c.b;
      }
      const lineGeo = new THREE.BufferGeometry();
      lineGeo.setAttribute('position', new THREE.BufferAttribute(edgePositions, 3));
      lineGeo.setAttribute('color', new THREE.BufferAttribute(edgeColors, 3));
      const lineMat = new THREE.LineBasicMaterial({ vertexColors: true, linewidth: P.lineWidth });
      const lineObj = new THREE.LineSegments(lineGeo, lineMat);
      group.add(lineObj);

      // Vertex point overlay
      const ptPositions = new Float32Array(P.vertices.length * 3);
      const ptColors = new Float32Array(P.vertices.length * 3);
      for (let i = 0; i < P.vertices.length; i++) {
        ptPositions[i * 3]     = P.vertices[i][0];
        ptPositions[i * 3 + 1] = P.vertices[i][1];
        ptPositions[i * 3 + 2] = 0;
        const c = parseColor(P.colors[i % P.colors.length]);
        ptColors[i * 3]     = c.r;
        ptColors[i * 3 + 1] = c.g;
        ptColors[i * 3 + 2] = c.b;
      }
      const ptGeo = new THREE.BufferGeometry();
      ptGeo.setAttribute('position', new THREE.BufferAttribute(ptPositions, 3));
      ptGeo.setAttribute('color', new THREE.BufferAttribute(ptColors, 3));
      const ptMat = new THREE.PointsMaterial({ size: P.particleSize, vertexColors: true, sizeAttenuation: true });
      const pts = new THREE.Points(ptGeo, ptMat);
      group.add(pts);

      // Glow layers (fake bloom)
      for (let g = 0; g < P.glowLayers; g++) {
        const s = 1.0 + (g + 1) * 0.02;
        const opacity = 0.12 / (g + 1);
        const glowLineMat = new THREE.LineBasicMaterial({ vertexColors: true, linewidth: P.lineWidth, transparent: true, opacity });
        const glowLine = new THREE.LineSegments(lineGeo.clone(), glowLineMat);
        glowLine.scale.setScalar(s);
        group.add(glowLine);
      }
    } else {
      // IFS point cloud
      const positions = new Float32Array(P.points.length * 3);
      const colors = new Float32Array(P.points.length * 3);
      for (let i = 0; i < P.points.length; i++) {
        positions[i * 3]     = P.points[i][0];
        positions[i * 3 + 1] = P.points[i][1];
        positions[i * 3 + 2] = 0;
        const c = parseColor(P.colors[i % P.colors.length]);
        colors[i * 3]     = c.r;
        colors[i * 3 + 1] = c.g;
        colors[i * 3 + 2] = c.b;
      }
      const geo = new THREE.BufferGeometry();
      geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
      geo.setAttribute('color', new THREE.BufferAttribute(colors, 3));
      const mat = new THREE.PointsMaterial({ size: P.particleSize, vertexColors: true, sizeAttenuation: true, transparent: true, opacity: 0.85 });
      const pts = new THREE.Points(geo, mat);
      group.add(pts);

      // Glow layers
      for (let g = 0; g < P.glowLayers; g++) {
        const s = 1.0 + (g + 1) * 0.025;
        const opacity = 0.10 / (g + 1);
        const glowMat = new THREE.PointsMaterial({ size: P.particleSize * (1.5 + g * 0.5), vertexColors: true, sizeAttenuation: true, transparent: true, opacity });
        const glowPts = new THREE.Points(geo.clone(), glowMat);
        glowPts.scale.setScalar(s);
        group.add(glowPts);
      }
    }

    // --- Mouse parallax ---
    let mouseX = 0, mouseY = 0;
    const onMouseMove = (e) => {
      mouseX = (e.clientX / window.innerWidth) * 2 - 1;
      mouseY = (e.clientY / window.innerHeight) * 2 - 1;
    };
    window.addEventListener('mousemove', onMouseMove);

    // --- Resize handler ---
    const onResize = () => {
      camera.aspect = window.innerWidth / window.innerHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(window.innerWidth, window.innerHeight);
    };
    window.addEventListener('resize', onResize);

    // --- Animation loop ---
    const animate = () => {
      animFrameRef.current = requestAnimationFrame(animate);
      const elapsed = clock.getElapsedTime();

      // Slow rotation
      group.rotation.y += P.animationSpeed * 0.003;

      // Breathing scale pulse
      group.scale.setScalar(1.0 + Math.sin(elapsed * P.animationSpeed * 0.4) * 0.04);

      // Mouse parallax (smooth lag)
      group.rotation.x += (mouseY * 0.3 - group.rotation.x) * 0.05 * P.parallaxStrength;
      group.rotation.z += (mouseX * 0.15 - group.rotation.z) * 0.05 * P.parallaxStrength;

      renderer.render(scene, camera);
    };
    animate();

    // --- Cleanup ---
    return () => {
      cancelAnimationFrame(animFrameRef.current);
      window.removeEventListener('resize', onResize);
      window.removeEventListener('mousemove', onMouseMove);
      renderer.dispose();
      if (container.contains(renderer.domElement)) {
        container.removeChild(renderer.domElement);
      }
    };
  }, []);

  return (
    <div
      ref={mountRef}
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100vw',
        height: '100vh',
        zIndex: -1,
        overflow: 'hidden',
      }}
    />
  );
}
"""


# ---------------------------------------------------------------------------
# Geometry extraction helpers
# ---------------------------------------------------------------------------

def extract_lsystem_geometry(segments, max_points=4000):
    """Extract and normalize L-system line segments for Three.js.

    Args:
        segments: List of (x1, y1, x2, y2) tuples from interpret_turtle().
        max_points: Maximum number of segments to keep.

    Returns:
        Dict with keys: type, vertices, edges, bounds, normalized_vertices.
    """
    if not segments:
        return {"type": "lsystem", "vertices": [], "edges": [],
                "bounds": {"min_x": 0, "max_x": 0, "min_y": 0, "max_y": 0},
                "normalized_vertices": []}

    # Sample if needed
    if len(segments) > max_points:
        step = len(segments) / max_points
        segments = [segments[int(i * step)] for i in range(max_points)]

    # Bounding box
    all_x = [v for s in segments for v in (s[0], s[2])]
    all_y = [v for s in segments for v in (s[1], s[3])]
    min_x, max_x = min(all_x), max(all_x)
    min_y, max_y = min(all_y), max(all_y)
    bounds = {"min_x": min_x, "max_x": max_x, "min_y": min_y, "max_y": max_y}

    # Normalize to [-1, 1]
    range_x = max_x - min_x if max_x != min_x else 1.0
    range_y = max_y - min_y if max_y != min_y else 1.0
    scale = max(range_x, range_y) / 2.0
    cx = (min_x + max_x) / 2.0
    cy = (min_y + max_y) / 2.0

    def norm(x, y):
        return [round((x - cx) / scale, 5), round((y - cy) / scale, 5)]

    vertices = []
    edges = []
    seen = set()
    for x1, y1, x2, y2 in segments:
        nx1, ny1 = norm(x1, y1)
        nx2, ny2 = norm(x2, y2)
        edges.append([nx1, ny1, nx2, ny2])
        for vx, vy in [(nx1, ny1), (nx2, ny2)]:
            key = (vx, vy)
            if key not in seen:
                seen.add(key)
                vertices.append([vx, vy])

    return {
        "type": "lsystem",
        "vertices": vertices,
        "edges": edges,
        "bounds": bounds,
        "normalized_vertices": vertices,
    }


def extract_ifs_geometry(points, max_points=6000):
    """Extract and normalize IFS point cloud for Three.js.

    Args:
        points: List of (x, y) tuples from the chaos game.
        max_points: Maximum number of points to keep.

    Returns:
        Dict with keys: type, points, density_hint.
    """
    if not points:
        return {"type": "ifs", "points": [], "density_hint": 0.0}

    total = len(points)

    # Sample if needed
    if total > max_points:
        step = total / max_points
        points = [points[int(i * step)] for i in range(max_points)]

    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)

    range_x = max_x - min_x if max_x != min_x else 1.0
    range_y = max_y - min_y if max_y != min_y else 1.0
    scale = max(range_x, range_y) / 2.0
    cx = (min_x + max_x) / 2.0
    cy = (min_y + max_y) / 2.0

    normalized = [
        [round((p[0] - cx) / scale, 5), round((p[1] - cy) / scale, 5)]
        for p in points
    ]

    return {
        "type": "ifs",
        "points": normalized,
        "density_hint": round(len(points) / max_points, 4),
    }


# ---------------------------------------------------------------------------
# Params serialisation + component generation
# ---------------------------------------------------------------------------

def build_threejs_params(geometry_dict, colors, animation_speed=1.0,
                         parallax_strength=0.4, particle_size=0.008,
                         glow_layers=2, bg_color="#0a0a0f", label=""):
    """Merge geometry data with UI config into a JavaScript object literal.

    Args:
        geometry_dict: Dict from extract_lsystem_geometry or extract_ifs_geometry.
        colors: List of hex colour strings.
        animation_speed: Float 0.1–2.0.
        parallax_strength: Float 0.0–1.0.
        particle_size: Float for THREE.PointsMaterial size.
        glow_layers: Integer 1–3.
        bg_color: Hex string for page background.
        label: Human-readable label for generated code comment.

    Returns:
        A string containing ``const INJECTED_PARAMS = { ... };``.
    """
    payload = {
        "type": geometry_dict["type"],
        "colors": colors,
        "animationSpeed": animation_speed,
        "parallaxStrength": parallax_strength,
        "particleSize": particle_size,
        "lineWidth": 1,
        "glowLayers": glow_layers,
        "backgroundColor": bg_color,
        "label": label,
    }

    if geometry_dict["type"] == "lsystem":
        payload["vertices"] = geometry_dict["vertices"]
        payload["edges"] = geometry_dict["edges"]
    else:
        payload["points"] = geometry_dict["points"]

    serialized = json.dumps(payload, separators=(",", ":"))

    # Enforce payload size limit
    if len(serialized.encode("utf-8")) > MAX_REACT_PAYLOAD_BYTES:
        # Truncate geometry arrays
        if "edges" in payload:
            keep = max(100, len(payload["edges"]) // 2)
            payload["edges"] = payload["edges"][:keep]
            payload["vertices"] = payload["vertices"][:keep]
        elif "points" in payload:
            keep = max(100, len(payload["points"]) // 2)
            payload["points"] = payload["points"][:keep]
        serialized = json.dumps(payload, separators=(",", ":"))
        st.warning(
            f"React payload exceeded {MAX_REACT_PAYLOAD_BYTES:,} bytes — "
            f"geometry was truncated to fit."
        )

    return f"const INJECTED_PARAMS = {serialized};"


def generate_react_component(injected_params_js, label=""):
    """Slot INJECTED_PARAMS into the stable React template.

    Args:
        injected_params_js: JS string from build_threejs_params().
        label: Human-readable label for the comment header.

    Returns:
        Complete JSX file contents as a Python string.
    """
    src = REACT_COMPONENT_TEMPLATE.replace(
        "{INJECTED_PARAMS_PLACEHOLDER}", injected_params_js
    )
    src = src.replace("{LABEL_COMMENT}", label)
    return src


def generate_iframe_html(react_source, bg_color="#0a0a0f"):
    """Build a self-contained HTML preview using Canvas 2D.

    This preview does NOT load any external scripts (React, Three.js, Babel).
    Instead it uses the browser's built-in Canvas 2D API to render the
    geometry with animation, glow, and mouse parallax — all inline.

    The downloadable .jsx file (react_source) still contains the full
    React + Three.js component.  This function only reads the
    INJECTED_PARAMS from that source to build the preview.

    Args:
        react_source: Complete JSX source (used to extract INJECTED_PARAMS).
        bg_color: Hex background colour for the page body.

    Returns:
        Complete HTML string ready for ``st.components.v1.html()``.
    """
    # Extract the INJECTED_PARAMS line from the react source
    params_line = ""
    for line in react_source.split("\n"):
        stripped = line.strip()
        if stripped.startswith("const INJECTED_PARAMS"):
            params_line = stripped
            break

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
html,body,canvas{{width:100%;height:100%;overflow:hidden;background:{bg_color};display:block}}
</style>
</head>
<body>
<canvas id="c"></canvas>
<script>
// --- Injected geometry and config ---
{params_line}
const P = INJECTED_PARAMS;

// --- Canvas setup ---
const canvas = document.getElementById('c');
const ctx = canvas.getContext('2d');
let W, H;
function resize() {{
  W = canvas.width = window.innerWidth;
  H = canvas.height = window.innerHeight;
}}
resize();
window.addEventListener('resize', resize);

// --- Mouse tracking ---
let mx = 0, my = 0;
window.addEventListener('mousemove', e => {{
  mx = (e.clientX / W) * 2 - 1;
  my = (e.clientY / H) * 2 - 1;
}});

// --- Parse hex color ---
function hexToRgb(hex) {{
  const r = parseInt(hex.slice(1,3),16);
  const g = parseInt(hex.slice(3,5),16);
  const b = parseInt(hex.slice(5,7),16);
  return [r, g, b];
}}

// --- Animation state ---
let angle = 0;
let parallaxX = 0, parallaxY = 0;
const startTime = performance.now();

// Pre-group geometry by color for batched drawing
const colorCount = P.colors.length;
let colorGroups;
if (P.type === 'lsystem') {{
  colorGroups = P.colors.map(() => ({{ edges: [], verts: [] }}));
  const edges = P.edges || [];
  for (let i = 0; i < edges.length; i++) colorGroups[i % colorCount].edges.push(edges[i]);
  const verts = P.vertices || [];
  for (let i = 0; i < verts.length; i++) colorGroups[i % colorCount].verts.push(verts[i]);
}} else {{
  colorGroups = P.colors.map(() => ([]));
  const pts = P.points || [];
  for (let i = 0; i < pts.length; i++) colorGroups[i % colorCount].push(pts[i]);
}}

function draw() {{
  const elapsed = (performance.now() - startTime) / 1000;

  // Clear
  ctx.fillStyle = P.backgroundColor || '{bg_color}';
  ctx.fillRect(0, 0, W, H);

  ctx.save();
  ctx.translate(W / 2, H / 2);

  // Mouse parallax (smooth lerp)
  parallaxX += (mx * 30 * (P.parallaxStrength || 0.4) - parallaxX) * 0.05;
  parallaxY += (my * 30 * (P.parallaxStrength || 0.4) - parallaxY) * 0.05;
  ctx.translate(parallaxX, parallaxY);

  // Breathing scale
  const breathe = 1.0 + Math.sin(elapsed * (P.animationSpeed || 1.0) * 0.4) * 0.04;
  ctx.scale(breathe, breathe);

  // Slow rotation
  angle += (P.animationSpeed || 1.0) * 0.002;
  ctx.rotate(angle);

  // Scale geometry to fit canvas (geometry is in [-1,1])
  const scale = Math.min(W, H) * 0.42;
  ctx.scale(scale, -scale);
  ctx.lineCap = 'round';

  if (P.type === 'lsystem') {{
    const lw = (P.lineWidth || 1) / scale;
    const ps = (P.particleSize || 0.008) * 2;

    // Glow pass: thicker + semi-transparent (no shadowBlur)
    ctx.globalAlpha = 0.15;
    ctx.lineWidth = lw * 4;
    for (let ci = 0; ci < colorCount; ci++) {{
      const grp = colorGroups[ci];
      if (!grp.edges.length) continue;
      ctx.strokeStyle = P.colors[ci];
      ctx.beginPath();
      for (const e of grp.edges) {{
        ctx.moveTo(e[0], e[1]);
        ctx.lineTo(e[2], e[3]);
      }}
      ctx.stroke();
    }}

    // Main pass: crisp lines
    ctx.globalAlpha = 1.0;
    ctx.lineWidth = lw;
    for (let ci = 0; ci < colorCount; ci++) {{
      const grp = colorGroups[ci];
      if (grp.edges.length) {{
        ctx.strokeStyle = P.colors[ci];
        ctx.beginPath();
        for (const e of grp.edges) {{
          ctx.moveTo(e[0], e[1]);
          ctx.lineTo(e[2], e[3]);
        }}
        ctx.stroke();
      }}
      // Vertex dots
      if (grp.verts.length) {{
        ctx.fillStyle = P.colors[ci];
        ctx.beginPath();
        for (const v of grp.verts) {{
          ctx.moveTo(v[0] + ps, v[1]);
          ctx.arc(v[0], v[1], ps, 0, Math.PI * 2);
        }}
        ctx.fill();
      }}
    }}

  }} else {{
    const ps = (P.particleSize || 0.012) * 1.5;

    // Glow pass
    ctx.globalAlpha = 0.12;
    for (let ci = 0; ci < colorCount; ci++) {{
      const pts = colorGroups[ci];
      if (!pts.length) continue;
      ctx.fillStyle = P.colors[ci];
      ctx.beginPath();
      for (const p of pts) {{
        ctx.moveTo(p[0] + ps * 2, p[1]);
        ctx.arc(p[0], p[1], ps * 2, 0, Math.PI * 2);
      }}
      ctx.fill();
    }}

    // Main pass
    ctx.globalAlpha = 0.85;
    for (let ci = 0; ci < colorCount; ci++) {{
      const pts = colorGroups[ci];
      if (!pts.length) continue;
      ctx.fillStyle = P.colors[ci];
      ctx.beginPath();
      for (const p of pts) {{
        ctx.moveTo(p[0] + ps, p[1]);
        ctx.arc(p[0], p[1], ps, 0, Math.PI * 2);
      }}
      ctx.fill();
    }}
    ctx.globalAlpha = 1.0;
  }}

  ctx.restore();
  requestAnimationFrame(draw);
}}
draw();
</script>
</body>
</html>"""
    return html
